name: Wikimedia CI Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test_and_lint:
    name: Code Quality & PySpark Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pyspark

      - name: Lint Code with Flake8
        run: |
          # stop if has critical syntax error Python
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run PySpark Tests
        run: |
          pytest tests/ -v
